# -*- coding: utf-8 -*-
"""Cópia de Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q5LhJQ4RBWRBYV9xWGIr-7We7tuOholY
"""

#faça um numero que leia 5 numeros e informe o maior numero
maior_numero = 0
for contador in range(5):
numero = int(input("digite um numero"))
if numero > maior_numero:
maior_numero=numero
 print(maior_numero)





#faça um programa que verifique e mostre os numeros entre 1000 e 2000
for contador in range(1000,2001):
  if contador % 11 ==2:
    print (contador )



# faça um programa que leia 5numeros e informe a soma e a media dos numeros
soma = 0
for i in range(5):
 numero =float(input (f"digite o {i+1} º numero:"))
 soma += numero
media = soma/5
print (f"a soma dos numeros e: {soma}")
print (f"a media dos numeros e: {media}")





#faça um programa que receba um numero e usando laços de repetição calcule e mostre a tabuada desse numero
numero = int(input("digite um numero para calcular a tabuada "))
print("tabuada de",numero,"")
for i in range(1,11):
 resultado = numero*i
 print(numero,"x",i,"=",resultado)

#faça um programa que mostre a tabuadas dos numeros de 1 a 10 usando laços de repetição
for i in range (1,11):
  for j in range(1,11):
    resultado i*j
   print("x",j, "=",resultado)

# faça um programa que imprima na tela os numeros de 1 a 20
for i in range(1, 21):
 print(i)

#faça um programa que imprima na tela apenas os impares entre 1 e 50
for i in range(1, 50):
 if i % 2==1:
  print(i)

#faça um programa que receba dois numeros inteiros e gere os numeros inteiros
n1 = int(input("digite um numero:"))
n2 = int(input("digite outro numero:"))
for u in range (n+1+1, n2):
  print(u)

#Uma loja deseja cadastrar 5 clientes e verificar se o faturamento da loja foi
lojaB = 54000
lojaA = 0

for i in range(5):
  valor = int(input("digite um valor"))
  lojaA += valor

if lojaB > lojaA:
  print("Loja b foi maior")
elif lojaB == lojaA:
  print("foi igual")
else:
  print("loja A foi maior")

#Faça um programa que peça 10 números inteiros, calcule e mostre a quantidade de números pares e a quantidade de números impares.
for i in range(10):
  numeros = input("digite um numero")
  if i % 2 == 1:
    print(i)
    print("esses numero sao impares")
  else:
    print("esses numeros sao pares")

#Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário
 for in range (1)
 Nota = float (input("digite uma nota de zero a dez"):)
  if nota > 0 and  nota < 10:
       print("nota valida")
  else:
       print("nota invalida,digite uma nota 0 a 10" )

#Uma loja tem tem uma política de descontos de acordo com o valor da compra do cliente. Os descontos começam acima dos R$500.
if valordacompra == 500:
  print("voce recebe 1% de desconto")
elif valordacompra == 600:
  print("voce recebeu 2% de desconto")
  elif valordacompra == 700:
  print("voce recebeu 3% de desconto")
  elif valordacompra == 800:
  print("voce recebeu 4% de desconto")
  elif valordacompra == 900:
  print("voce recebeu 5% de desconto")
  elif valordacompra == 1000:
  print("voce recebeu 6% de desconto")
  elif valordacompra == 1100:
  print("voce recebeu 7% de desconto")
  elif valordacompra == 1200:
  print("voce recebeu 8% de desconto")
  elif valordacompra == 1300:
  print("voce recebeu 9% de desconto")
  elif valordacompra == 1400:
  print("voce recebeu 10% de desconto")
   elif valordacompra == 1500:
  print("voce recebeu 11% de desconto")
   elif valordacompra == 1600:
  print("voce recebeu 12% de desconto")
   elif valordacompra == 1700:
  print("voce recebeu 13% de desconto")
   elif valordacompra == 1800:
  print("voce recebeu 14% de desconto")
   elif valordacompra == 1900:
  print("voce recebeu 15% de desconto")
   elif valordacompra == 2000:
  print("voce recebeu 16% de desconto")
  elif valordacompra == 2100:
  print("voce recebeu 17% de desconto")
  elif valordacompra == 2200:
  print("voce recebeu 18% de desconto")
  elif valordacompra == 2300:
  print("voce recebeu 19% de desconto")
  elif valordacompra == 2400:
  print("voce recebeu 20% de desconto")
  elif valordacompra == 2500:
  print("voce recebeu 21% de desconto")
  elif valordacompra == 2600:
  print("voce recebeu 22% de desconto")
  elif valordacompra == 2700:
  print("voce recebeu 23% de desconto")
  elif valordacompra == 2800:
  print("voce recebeu 24% de desconto")
  elif valordacompra == 2900:
  print("voce recebeu 25% de desconto")

#Faça um programa que receba a idade de 15 pessoas e que calcule e mostre:
faixas_etarias = [15, 16/30, 31/45, 46/60, 61+]
 total_pessoas = len(idades)

for idade in idades:
    if idade <= 17:
        faixas_etarias[0] += 1
    elif 18 <= idade <= 29:
        faixas_etarias[1] += 1
    elif 30 <= idade <= 49:
        faixas_etarias[2] += 1
    elif 50 <= idade <= 64:
        faixas_etarias[3] += 1
    else:
        faixas_etarias[4] += 1

#Faça um programa que peça dois números, base e expoente, calcule e mostre o primeiro número elevado ao segundo número.
base = float(input("Digite a base: "))
expoente = int(input("Digite o expoente: "))

resultado = 1

for _ in range(expoente):
    resultado *= base

print(f"{base} elevado a {expoente} é igual a {resultado}")

#Faça um programa que mostre todos os primos entre 1 e N sendo N um número inteiro fornecido pelo usuário.
N = int(input("Digite um número inteiro "))
primos = []
divisoes = 0

for num in range(2, N + 1):
    primo = True
    for i in range(2, int(num**0.5) + 1):
        divisoes += 1
        if num % i == 0:
            primo = False
            break
    if primo:
        primos += [num]

print("Números primos entre 1 e", N, primos)
print("Número total de divisões realizadas:", divisoes)




